---
include:
  - board: ergohaven
    shield: imperial44_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: ergohaven
    shield: imperial44_left
    keymap: imperial44_ruen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: imperial44_left_ruen-ergohaven-zmk
  - board: ergohaven
    shield: imperial44_right
